name: Idea
description: Suggest a lesson, a word or a feature
title: "[idea] "
labels: [idea]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true
